### PR TITLE
Update UG with screenshots

### PR DESCRIPTION
**Pull request by stanley-1**
I generated a jar file based on the latest codes available on the master branch. After loading the app and reviewing the sample data listed, I have modified some of the existing examples in the UG so that the capturing of screenshots will be smoother. 

Is it possible for @EssWhyy to capture the screenshots once you're done with the UI update and the relevant PRs have been merged? Generally, let's try to insert a screenshot for the first example of each feature. 

On a side note, we might have to make certain phrasings more "user-centric" to meet CS2101's expectations.

### CODE REVIEW

**Review by EssWhyy — APPROVED** [review]
Thanks! Will take the screenshots by tomorrow morning if no one has done it yet.

**Comment by stanley-1** [comment]
Marked as draft while screenshots are being added to the UG. A screenshot will be appended to the first example of each feature/command. Will reopen for review once this process is complete.

**Comment by stanley-1** [comment]
@AY2122S1-CS2103T-F11-4/developers Here's the updated UG with pictures included. You may browse it at this [link](https://stanley-1.github.io/tp/UserGuide.html).

**Review by david-eom — APPROVED** [review]
LGTM! Thanks for the contribution to UG so far Stanley!

**Review by Zacchua — APPROVED** [review]
Nice UG looks rly good now thanks Stanley!

**Pull request merged**
