### PR TITLE
Add test cases for various classes

### PR DESCRIPTION
**Pull request by david-eom**

### CODE REVIEW

**Comment by david-eom** [comment]
For some reason, this PR is currently failing CI although it passes `gradle clean build` on local machine. Have absolutely no idea what the error message means, if anyone has idea pls kindly advise!!!!

截圖 2021-11-04 上午4 25 54

**Comment by david-eom** [comment]
Checking of `GraphicsEnvironment.isHeadless()` in `ShareCommandTest` is necessary, or else `java.awt.HeadlessException` will be thrown due to the absence of keyboard/mouse in GitHub CI environment.

**Review by EssWhyy — APPROVED** [review]
Nice work adding tests for Command History, didn't cover this in my previous PR so this will help to improve coverage more!

**Review by bnjmnt4n — APPROVED** [review]
Looks good, very extensive and thorough!

**Pull request merged**
